language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
script:
  - echo "imagine tests here"
after_success:
  - npm run semantic-deploy || true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
